#!/bin/bash
#
#
# Run as a root's crontab job every 4 hours by writing this after invoking the command crontab -e
#
#SHELL=/bin/bash
#PATH=/root/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#
#00 */4  * * *   /root/sbin/ssdtrim
#
# crontab file is missing newline before EOF, can't install.

LOG=/var/log/ssdtrim.log

trimcmd=$(which fstrim)

echo -en "\e[1;34m::\e[0;34m Disk trimming operation is in progress. Please wait..."

trimbootmsg=$(${trimcmd} -v /boot)
trimrootmsg=$(${trimcmd} -v /)
trimhomemsg=$(${trimcmd} -v /home)
trimzionmsg=$(${trimcmd} -v /media/ZionHome)

echo

trimmsg="${trimbootmsg#*: } from /boot partition
${trimrootmsg#*: } from / partition
${trimhomemsg#*: } from /home partition
${trimzionmsg#*: } from apricity/home partition"

if [[ ${trimmsg} ]]; then
	echo "$trimmsg on $(date -R) " | tee -a $LOG
else
	echo "Something went wrong with the trim function on $(date -R) " | tee -a $LOG
fi

exit $?
