#!/bin/bash
#
#
# Run as a root's crontab job every 4 hours by writing this after invoking the command crontab -e
#
#SHELL=/bin/bash
#PATH=/root/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#
#00 */4  * * *   /root/sbin/ssdtrim
#
# crontab file is missing newline before EOF, can't install.

LOG=/var/log/ssdtrim.log

trimcmd=$(which fstrim)

# Turns OFF the cursor
echo -en "\e[?25l"

echo -en "\e[1;34m::\e[0;34m Disk trimming operation is in progress. Please wait...\e[0;97m"

trimbootmsg=$(${trimcmd} -v /boot)
trimrootmsg=$(${trimcmd} -v /)
trimhomemsg=$(${trimcmd} -v /home)
trimzionmsg=$(${trimcmd} -v /run/media/jag/ZionHome)

echo

trimmsg="${trimbootmsg#*: } from\t/boot partition
${trimrootmsg#*: } from\t/ partition
${trimhomemsg#*: } from\t/home partition
${trimzionmsg#*: } from\tapricity/home partition"

if [[ ${trimmsg} ]]; then
	echo -e "$trimmsg on $(date -R) " | tee -a $LOG
else
	echo -en "\e[1;31m"
	echo "Something went wrong with the trim function on $(date -R) " | tee -a $LOG
fi
echo -en "\e[0m"

# Turns ON the cursor
echo -en "\e[?25h"

exit $?
