#!/bin/bash
#
#
# Run as a root's crontab job every 4 hours by writing this after invoking the command crontab -e
#
#SHELL=/bin/bash
#PATH=/root/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
#
#00 */4  * * *   /root/sbin/ssdtrim
#
# crontab file is missing newline before EOF, can't install.

LOG=/var/log/ssdtrim.log

trimcmd=$(which fstrim)

trimbootmsg=$(${trimcmd} -v /boot)
trimrootmsg=$(${trimcmd} -v /)

trimmsg="${trimbootmsg#*: } from /boot and ${trimrootmsg#*: } from / partition"

if [[ ${trimmsg} ]]; then
	echo "$trimmsg on $(date -R) " >> $LOG
else
	echo "Something went wrong with the trim function on $(date -R) " >> $LOG
fi

exit $?
